# 端口
server:
  port: 9002

# 应用名
spring:
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 # 连接到sentinel服务地址
      eager: true # 立即加载信息

# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ # Eureka server url
  instance:
    prefer-ip-address: true # 使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 实例id

# 配置Hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 服务调用触发熔断超时时间，默认1s